backscatter_coefficient:
  min: 0
  zmin: 0
  colorbar: KT_turbid
beam_c:
  min: 0
  zmin: 0
  colorbar: KT_turbid
beta_470nm:
  min: 0
  zmin: 0
  colorbar: KT_turbid
beta_532nm:
  min: 0
  zmin: 0
  colorbar: KT_turbid
beta_532nm_signal:
  min: 0
  zmin: 0
  colorbar: KT_turbid
beta_660nm:
  min: 0
  zmin: 0
  colorbar: KT_turbid
beta700:
  min: 0
  zmin: 0
  colorbar: KT_turbid
beta_700nm:
  min: 0
  zmin: 0
  colorbar: KT_turbid
beta_880nm:
  min: 0
  zmin: 0
  colorbar: KT_turbid
cdom:
  min: 0
  zmin: 0
  colorbar: KT_turbid
chlorophyll_a:
  min: 0
  zmin: 0
  colorbar: KT_algae
conductivity:
  zmin: 0
  colorbar: KT_haline
conductivity2:
  zmin: 0
  colorbar: KT_haline
density:
  zmin: 0
  colorbar: KT_dense
density2:
  zmin: 0
  colorbar: KT_dense
downwelling_par_irradiance:
  zmin: 0
  colorbar: KT_solar
nitrate_concentration:
  min: 0
  zmin: 0
  colorbar: KT_tempo
oxygen_concentration:
  zmin: 0
  colorbar: KT_oxy
oxygen_concentration_shifted:
  zmin: 0
  colorbar: KT_oxy
oxygen_saturation:
  zmin: 0
  colorbar: KT_oxy
potential_temperature:
  zmin: 0
  colorbar: KT_thermal
potential_temperature2:
  zmin: 0
  colorbar: KT_thermal
salinity:
  zmin: 0
  colorbar: KT_haline
salinity2:
  zmin: 0
  colorbar: KT_haline
sound_speed:
  zmin: 0
  colorbar: KT_speed
sound_speed2:
  zmin: 0
  colorbar: KT_speed
temperature:
  zmin: 0
  colorbar: KT_thermal
temperature2:
  zmin: 0
  colorbar: KT_thermal
sci_lisst_meansize:
  zmin: 0
  min: 0
  colorbar: KT_turbid
sci_lisst_totvol:
  zmin: 0
  min: 0
  colorbar: KT_turbid
sci_fl3slo_phyco_units:
  zmin: 0
  min: 0
  colorbar: KT_algae
sci_fl3slo_chlor_units:
  zmin: 0
  min: 0
  colorbar: KT_algae
sci_fl3slo_cdom_units:
  zmin: 0
  min: 0
  colorbar: KT_algae
